function randomLanguageName() {
  const allLanguages = [
    "English",
    "Bangla",
    "Hindi",
    "French",
    "German",
    "Japanese",
    "Chinese",
    "Aari",
    "Aasáx",
    "Abaza",
    "Abellen",
    "Abenaki",
    "Abkhaz",
    "Abui",
    "Abure",
    "Achang",
    "Adai",
    "Arabela",
    "Espanol",
    "Nepali",
    "Bodo",
    "Buhid",
    "Buginese",
    "Dutch",
    "Gallo",
    "Greek",
    "Gujrati",
    "Hausa",
    "Irish",
    "Baharain",
    "Urdu",
    "Marathi",
    "Marwari",
    "Mongolian",
    "Pahari",
    "Vietnamese",
    "Venetian",
    "Xhosa",
    "Xibe",
    "Xucuru",
    "Zulu",
    "Rajasthani",
    "Russian",
    "Tamil",
    "Yapese",
    "Yanesha",
    "Yiddish",
    "Zaza",
    "Bikol",
    "Big Nambas",
  ]
  const randomIndex = Math.round(Math.random() * 50)
  return allLanguages[randomIndex]
}

module.exports = randomLanguageName
